### ISSUE TITLE
As a user, I want to be able to duplicate the program

### ISSUE THREAD

**Issue by FitGirl-Omaha** [uno-isqa-8950/fitgirl-inc#323] opened 2019-01-07 20:47 UTC
Need to be able to duplicate all questions and images to each seasonal session without having to manually copy and paste one page at a time.
Spring 2019 - Fall 2019

**Comment by jlofshultuno** [comment] 2019-02-23 00:08
Duplicate of #343

**Closed by jlofshultuno** 2019-02-23 00:08 UTC
Labels: enhancement
